In [234]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [235]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "/Users/vrindapatel/Desktop/CryptoClustering/Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                    
bitcoin                              1.08388                     7.60278   
ethereum                             0.22392                    10.38134   
tether                              -0.21173                     0.04935   
ripple                              -0.37819                    -0.60926   
bitcoin-cash                         2.90585                    17.09717   
binancecoin                          2.10423                    12.85511   
chainlink                           -0.23935                    20.69459   
cardano                              0.00322                    13.99302   
litecoin                            -0.06341                     6.60221   
bitcoin-cash-sv                      0.92530                     3.29641   

                 price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                     
bitcoin                              6.57509                      7.67258   
ethereum                             4.80849                      0.13169   
tether                               0.00640                     -0.04237   
ripple                               2.24984                      0.23455   
bitcoin-cash                        14.75334                     15.74903   
binancecoin                          6.80688                      0.05865   
chainlink                            9.30098                    -11.21747   
cardano                              5.55476                     10.10553   
litecoin                             7.28931                      1.21662   
bitcoin-cash-sv                     -1.86656                      2.88926   

                 price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                      
bitcoin                             -3.25185                      83.51840   
ethereum                           -12.88890                     186.77418   
tether                               0.28037                      -0.00542   
ripple                             -17.55245                      39.53888   
bitcoin-cash                       -13.71793                      21.66042   
binancecoin                         36.33486                     155.61937   
chainlink                          -43.69522                     403.22917   
cardano                            -22.84776                     264.51418   
litecoin                           -17.23960                      27.49919   
bitcoin-cash-sv                    -24.87434                       7.42562   

                 price_change_percentage_1y  
coin_id                                      
bitcoin                            37.51761  
ethereum                          101.96023  
tether                              0.01954  
ripple                            -16.60193  
bitcoin-cash                       14.49384  
binancecoin                        69.69195  
chainlink                         325.13186  
cardano                           156.09756  
litecoin                          -12.66408  
bitcoin-cash-sv                    93.73082

In [236]:
# Generate summary statistics
df_market_data.describe()

price_change_percentage_24h  price_change_percentage_7d  \
count                    41.000000                   41.000000   
mean                     -0.269686                    4.497147   
std                       2.694793                    6.375218   
min                     -13.527860                   -6.094560   
25%                      -0.608970                    0.047260   
50%                      -0.063410                    3.296410   
75%                       0.612090                    7.602780   
max                       4.840330                   20.694590   

       price_change_percentage_14d  price_change_percentage_30d  \
count                    41.000000                    41.000000   
mean                      0.185787                     1.545693   
std                       8.376939                    26.344218   
min                     -18.158900                   -34.705480   
25%                      -5.026620                   -10.438470   
50%                       0.109740                    -0.042370   
75%                       5.510740                     4.578130   
max                      24.239190                   140.795700   

       price_change_percentage_60d  price_change_percentage_200d  \
count                    41.000000                     41.000000   
mean                     -0.094119                    236.537432   
std                      47.365803                    435.225304   
min                     -44.822480                     -0.392100   
25%                     -25.907990                     21.660420   
50%                      -7.544550                     83.905200   
75%                       0.657260                    216.177610   
max                     223.064370                   2227.927820   

       price_change_percentage_1y  
count                   41.000000  
mean                   347.667956  
std                   1247.842884  
min                    -17.567530  
25%                      0.406170  
50%                     69.691950  
75%                    168.372510  
max                   7852.089700

In [237]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [238]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the csv file.
model = StandardScaler()
normalized_data = model.fit_transform(df_market_data)
df_market_data_normalized = pd.DataFrame(normalized_data, columns=df_market_data.columns, index=df_market_data.index)
df_market_data_normalized.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  
coin_id                                   
bitcoin                        -0.251637  
ethereum                       -0.199352  
tether                         -0.282061  
ripple                         -0.295546  
bitcoin-cash                   -0.270317

In [239]:
# # Create a DataFrame with the scaled data
df_scaled = pd.DataFrame(normalized_data, columns=df_market_data.columns, index=df_market_data.index)

# Copy the crypto names from the original data
df_scaled['coin_id'] = df_market_data.index

# Set the coin_name column as index
df_scaled.set_index('coin_id', inplace=True)

# Display sample data
df_scaled.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  
coin_id                                   
bitcoin                        -0.251637  
ethereum                       -0.199352  
tether                         -0.282061  
ripple                         -0.295546  
bitcoin-cash                   -0.270317

---

### Find the Best Value for k Using the Original Data.

In [240]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1, 12))


In [241]:
# Create an empty list to store the inertia values
# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list

inertia = []
for i in k:
    model = KMeans(n_clusters=i, random_state=0)
    model.fit(df_scaled)
    inertia.append(model.inertia_)

In [242]:
# Create a dictionary with the data to plot the Elbow curve

elbow_data = {
    "K": k,
    "inertia": inertia
}

# create a DataFrame with the data to plot the Elbow curve
df_elbow = pd.DataFrame(elbow_data)

# Display the DataFrame
df_elbow

K     inertia
0    1  287.000000
1    2  198.571818
2    3  145.635748
3    4   79.022435
4    5   66.217780
5    6   59.139070
6    7   48.406314
7    8   38.993588
8    9   34.400595
9   10   28.573603
10  11   23.890044

In [243]:


# Plot the Elbow curve
df_elbow.hvplot.line(
    x='K',
    y='inertia',
    title='Elbow Curve',
    xticks=k,
    width=800,
    height=400
)

:Curve   [K]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** Looking at the Elbow Curve graph, it appears that the “elbow” point occurs around (k = 4). This means that increasing the number of clusters beyond 4 results in diminishing returns in terms of reducing inertia (within-cluster sum of squares). Therefore, (k = 4) seems to be the best value based on this analysis.


---

### Cluster Cryptocurrencies with K-means Using the Original Data

In [244]:
# Initialise the K-Means model using the best value for K
model = KMeans(n_clusters=4, random_state=0)


In [245]:
# Fit the model to the data
model.fit(df_scaled)

KMeans(n_clusters=4, random_state=0)

In [246]:
# Predict the clusters
predictions = model.predict(df_scaled)

# Print the result array of cluster value
print(predictions)

[2 2 0 0 2 2 2 2 2 0 0 0 0 2 0 2 0 0 2 0 0 2 0 0 0 0 0 0 2 0 0 0 1 2 0 0 3
 0 0 0 0]


In [247]:
# Create a copy of Dataframe
df_market_data_clustered = df_market_data.copy()

In [248]:
# Add a new column to the DataFrame with the predicted clusters
df_market_data_clustered["Predicted Cluster"] = model.labels_

# Display sample data
df_market_data_clustered.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                           1.08388                     7.60278   
ethereum                          0.22392                    10.38134   
tether                           -0.21173                     0.04935   
ripple                           -0.37819                    -0.60926   
bitcoin-cash                      2.90585                    17.09717   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                           6.57509                      7.67258   
ethereum                          4.80849                      0.13169   
tether                            0.00640                     -0.04237   
ripple                            2.24984                      0.23455   
bitcoin-cash                     14.75334                     15.74903   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                          -3.25185                      83.51840   
ethereum                        -12.88890                     186.77418   
tether                            0.28037                      -0.00542   
ripple                          -17.55245                      39.53888   
bitcoin-cash                    -13.71793                      21.66042   

              price_change_percentage_1y  Predicted Cluster  
coin_id                                                      
bitcoin                         37.51761                  2  
ethereum                       101.96023                  2  
tether                           0.01954                  0  
ripple                         -16.60193                  0  
bitcoin-cash                    14.49384                  2

In [249]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Colour the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point
df_market_data_clustered.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="Predicted Cluster",
    hover_cols=["coin_name"]
)

:NdOverlay   [Predicted Cluster]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d)

---

### Optimise Clusters with Principal Component Analysis.

In [250]:
# Create a PCA model instance and set `n_components=3'.
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [251]:
# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
market_data_pca = pca.fit_transform(df_scaled)

# Create a DataFrame with the principal component values
df_market_data_pca = pd.DataFrame(market_data_pca, columns=["PC1", "PC2", "PC3"])

# Display sample data
df_market_data_pca.head()

PC1       PC2       PC3
0 -0.600667  0.842760  0.461595
1 -0.458261  0.458466  0.952877
2 -0.433070 -0.168126 -0.641752
3 -0.471835 -0.222660 -0.479053
4 -1.157800  2.041209  1.859715

In [252]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.3719856 , 0.34700813, 0.17603793])

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** Based on the provided explained variance ratios, the total explained variance of the three principal components is approximately 89.5%.

**Total explained variance = explained_variance[0] + explained_variance[1] + explained_variance[2] = 0.3719856 + 0.34700813 + 0.17603793 = 0.89503166**

Therefore, the total explained variance of the three principal components is approximately 0.895 or 89.49%. This indicates that the three principal components capture a significant portion of the variability in the original data.

In [253]:
# Create a new DataFrame with the PCA data.
# Creating a DataFrame with the PCA data
# Copy the crypto names from the original data
# Set the coinid column as index
# Display sample data

df_market_data_pca["coin_id"] = df_market_data.index
df_market_data_pca.set_index("coin_id", inplace=True)
df_market_data_pca.head()


PC1       PC2       PC3
coin_id                                   
bitcoin      -0.600667  0.842760  0.461595
ethereum     -0.458261  0.458466  0.952877
tether       -0.433070 -0.168126 -0.641752
ripple       -0.471835 -0.222660 -0.479053
bitcoin-cash -1.157800  2.041209  1.859715

---

### Find the Best Value for k Using the PCA Data

In [254]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1, 12))

In [255]:
# Create an empty list to store the inertia values


# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list
inertia = []
for i in k:
    model = KMeans(n_clusters=i, random_state=0)
    model.fit(df_market_data_pca)
    inertia.append(model.inertia_)
    

In [256]:
# Create a dictionary with the data to plot the Elbow curve
elbow_data = {
    "K": k,
    "inertia": inertia
}

# Create a DataFrame with the data to plot the Elbow curve
df_elbow_K = pd.DataFrame(elbow_data)

# Display the DataFrame
df_elbow_K

K     inertia
0    1  256.874086
1    2  168.811896
2    3  115.918077
3    4   49.665497
4    5   41.357314
5    6   30.796642
6    7   25.915457
7    8   21.890936
8    9   17.720699
9   10   13.838699
10  11    7.984355

In [257]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for K
df_elbow_K.hvplot.line(
    x='K',
    y='inertia',
    title='Elbow Curve',
    xticks=k,
    width=800,
    height=400
)

:Curve   [K]   (inertia)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:**The Elbow curve suggests that around 4 clusters would be a reasonable choice for k. Beyond that point, the reduction in inertia becomes less significant.


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:** It seems that the K-values remain consistent with the original data, but the inertia values are lower.

### Cluster Cryptocurrencies with K-means Using the PCA Data

In [258]:
# Initialise the K-Means model using the best value for K
model = KMeans(n_clusters=4, random_state=0)

In [259]:
# Fit the K-Means model using the PCA data
model.fit(df_market_data_pca)

# Predict the clusters
predictions = model.predict(df_market_data_pca)

# Print the result array of cluster value
print(predictions)

[2 2 0 0 2 2 2 2 2 0 0 0 0 2 0 2 0 0 2 0 0 2 0 0 0 0 0 0 2 0 0 0 1 2 0 0 3
 0 0 0 0]


In [272]:
# Create a copy of the DataFrame with the PCA data
df_market_data_clustered_PC = df_market_data_pca.copy()

# Add a new column to the DataFrame with the predicted clusters
df_market_data_clustered_PC["Predicted Cluster"] = model.labels_

# Display sample data
df_market_data_clustered_PC.head()

PC1       PC2       PC3  Predicted Cluster
coin_id                                                      
bitcoin      -0.600667  0.842760  0.461595                  2
ethereum     -0.458261  0.458466  0.952877                  2
tether       -0.433070 -0.168126 -0.641752                  0
ripple       -0.471835 -0.222660 -0.479053                  0
bitcoin-cash -1.157800  2.041209  1.859715                  2

In [273]:
# Create a scatter plot using hvPlot by setting 
# `x="PC1"` and `y="PC2"`. 
# Colour the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.
df_market_data_clustered_PC.hvplot.scatter(
    x="PC1",
    y="PC2",
    by="Predicted Cluster",
    hover_cols=["coin_id"]
)

:NdOverlay   [Predicted Cluster]
   :Scatter   [PC1]   (PC2,coin_id)

### Visualise and Compare the Results

In this section, you will visually analyse the cluster analysis results by contrasting the outcome with and without using the optimisation techniques.

In [262]:
# Composite plot to contrast the Elbow curves for the original data and the PCA data
df_elbow.hvplot.line(
    x='K',
    y='inertia',
    title='Elbow Curve',
    xticks=k,
    width=800,
    height=400
) * df_elbow_K.hvplot.line(
    x='K',
    y='inertia',
    title='Elbow Curve',
    xticks=k,
    width=800,
    height=400
)

:Overlay
   .Curve.I  :Curve   [K]   (inertia)
   .Curve.II :Curve   [K]   (inertia)

In [275]:
# Create a DataFrame with the original data and the predicted clusters
df_market_data_clustered = df_market_data.copy()
df_market_data_clustered["Predicted Cluster"] = model.labels_

# Display sample data
df_market_data_clustered.head()

# composite plot to contrast the scatter plots for the original data and the PCA data
df_market_data_clustered.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="Predicted Cluster",
    hover_cols=["coin_name"]
) + df_market_data_clustered_PC.hvplot.scatter(
    x="PC1",
    y="PC2",
    by="Predicted Cluster",
    hover_cols=["coin_name"]
)


:Layout
   .NdOverlay.I  :NdOverlay   [Predicted Cluster]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d)
   .NdOverlay.II :NdOverlay   [Predicted Cluster]
      :Scatter   [PC1]   (PC2)

In [276]:
df_market_data_clustered.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="Predicted Cluster",
    hover_cols=["coin_name"]
) * df_market_data_clustered_PC.hvplot.scatter(
    x="PC1",
    y="PC2",
    by="Predicted Cluster",
    hover_cols=["coin_name"]
)

:Overlay
   .NdOverlay.I  :NdOverlay   [Predicted Cluster]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d)
   .NdOverlay.II :NdOverlay   [Predicted Cluster]
      :Scatter   [PC1]   (PC2)

#### Answer the following question: 

  * **Question:** After visually analysing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** 
*Reduced Dimensionality:
Reducing the number of features simplifies the clustering process by focusing on essential aspects of the data and eliminating noise.
It can lead to more efficient computations for high-dimensional data.

*Loss of Information:
Using fewer features may result in lost information, affecting clustering accuracy.
Relevant patterns or crucial structural information might be discarded.

*Increased Interpretability:
Fewer features make resulting clusters easier to interpret and understand.
Visualizing and explaining clusters becomes less challenging.

*Improved Scalability:
Clustering algorithms, like K-Means, can be computationally expensive for high-dimensional data.
Reducing features enhances scalability, allowing larger datasets to be processed efficiently.

*Feature Selection Sensitivity:
Carefully choosing relevant features is critical when using fewer dimensions.
Poor feature selection negatively impacts clustering results.
Remember that the impact of reduced dimensionality depends on the specific dataset and clustering goals.